---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
- type: text
  name: price
  label: price
- type: text
  name: discount_price
  label: discount_price
- type: tag_list
  name: colors
  label: colors
- type: tag_list
  name: sizes
  label: sizes
pages:
- exampleSite/content/english/products/automatic-reflectance-measurement.md
- exampleSite/content/english/products/automatic-transmission-measurement.md
- exampleSite/content/english/products/ball-mills.md
- exampleSite/content/english/products/camsizer-p4.md
- exampleSite/content/english/products/camsizer-x2.md
- exampleSite/content/english/products/camsizer-xl.md
- exampleSite/content/english/products/cutting-mills.md
- exampleSite/content/english/products/disc-mills.md
- exampleSite/content/english/products/drum-mill-tm500.md
- exampleSite/content/english/products/jaw-crusher.md
- exampleSite/content/english/products/knife-mill.md
- exampleSite/content/english/products/mortar-grinder.md
- exampleSite/content/english/products/online-colorimeter.md
- exampleSite/content/english/products/partan-3d.md
- exampleSite/content/english/products/rotor-mill.md
- exampleSite/content/english/products/sieve-shakers.md
- exampleSite/content/english/products/the-sample-divider-pt-100.md
- exampleSite/content/english/products/the-vibratory-feeder-dr-100.md
